title: "Javier Sainz Villalba"
email: "javiervsainz@gmail.com"
description: "Biomedical engineer MSc"
baseurl: "" # se debe dejar vacío para GitHub Pages
url: "https://javiersainzvillalba.github.io/" # URL de tu repositorio
header_pages:
  - resume.md
  - publications.md
  - talks.md
  - teaching.md
  - portfolio.md
  - blog.md


